Repository Eugeeun/NFE1-1-3-DevPorest_Frontend, pull requests merged in 2024-11, with the labels that each got.

#49 [FEAT] 기술스택2 컴포넌트 추가
  src/components/DevProfile/DevProfile.tsx
  src/components/Dropdown/Dropdown.tsx
  src/components/Dropdown/DropdownWithBtn.tsx
  src/components/TechStack/TechStack.styles.ts
  src/components/TechStack/TechStack.tsx
  src/components/TechStack2/TechStack2.styles.ts
  src/components/TechStack2/TechStack2.tsx
  src/data/dummyData.ts
  src/data/mainPageData.ts
  src/data/profilePageData.ts
  src/pages/Detail/DetailPage.tsx
  src/pages/EditPortfolio/EditPortfolioPage.tsx
  src/pages/EditProfile/EditProfilePage.tsx
  src/pages/Profile/ProfilePage.tsx
Labels: ✨ Feature, 🎨 Html&css

#52 [FEAT] 직무별 기술스택 필터링 기능 추가
  src/data/dummyData.ts
  src/pages/Search/SearchPage.styles.ts
  src/pages/Search/SearchPage.tsx
Labels: ✨ Feature

#59 Prettier, ESLint 패키지 설치 및 환경 설정
  .gitignore
  eslint.config.js
  package-lock.json
  package.json
Labels: ⚙ Setting

#61 [FEAT] 프로필 등록 페이지 기능 추가
  .gitignore
  src/api/create-profile.ts
  src/api/get-job-group.ts
  src/api/get-tech-stacks.ts
  src/api/get-user-profile.ts
  src/api/upload-single-img.ts
  src/components/Dropdown/Dropdown.tsx
  src/components/Dropdown/DropdownWithBtn.tsx
  src/data/dummyData.ts
  src/pages/EditPortfolio/EditPortfolioPage.tsx
  src/pages/EditProfile/EditProfilePage.styles.ts
  src/pages/EditProfile/EditProfilePage.tsx
  src/pages/EditProfile/InfoInput.styles.ts
  src/pages/EditProfile/InfoInput.tsx
  src/pages/EditProfile/UserInfoInputs.tsx
  src/pages/Search/SearchPage.tsx
  src/styles/theme.ts
  src/types/api-types/UserType.ts
  src/types/job.ts
  src/utils/validInput.ts
Labels: ✨ Feature, 🎨 Html&css, 📬 API

#65 [FEAT] 검색 페이지 기능 추가
  src/api/create-profile.ts
  src/api/get-job-group.ts
  src/api/get-portfolios.ts
  src/api/get-tech-stacks.ts
  src/api/get-user-profile.ts
  src/api/upload-single-img.ts
  src/components/EmptyPortfolio/EmptyPortfolio.tsx
  src/components/PortfolioCard/PortfolioCard.tsx
  src/data/dummyPortfolioData.ts
  src/pages/EditProfile/UserInfoInputs.tsx
  src/pages/Search/SearchPage.styles.ts
  src/pages/Search/SearchPage.tsx
  src/pages/login/GithubLoginBtn/GithubLoginBtn.tsx
  src/store/store-search-page.ts
  src/types/api-types/PortfolioType.ts
  src/types/api-types/UserType.ts
  src/utils/build-search-query.ts
  src/utils/valid-input.ts
Labels: ✨ Feature, 📬 API

#68 [Feat] 프로필 페이지 기능 추가
  src/App.tsx
  src/api/get-user-portfolio.ts
  src/api/get-user-profile.ts
  src/data/profilePageData.ts
  src/pages/Profile/ProfilePage.style.tsx
  src/pages/Profile/ProfilePage.tsx
  src/pages/Profile/UserDetails.style.tsx
  src/types/api-types/PortfolioType.ts
Labels: ✨ Feature, 📬 API

#69 [Feat] 메인페이지 1,3,4 섹션 기능 추가
  src/api/get-tech-stacks.ts
  src/api/get-user-profile.ts
  src/components/DevProfile/DevProfile.styles.ts
  src/components/PortfolioCard/PortfolioCard.style.tsx
  src/pages/main/GraphSection.tsx
  src/pages/main/PopularDeveloperSection.tsx
  src/pages/main/PopularPortfolioSection.tsx
  src/types/api-types/TechStackType.ts
Labels: ✨ Feature, 📬 API

#71 [FEAT] ky Instance 생성 및 로그인 로직 구현
  src/api/index.ts
  src/pages/login/GithubLoginBtn/GithubLoginBtn.tsx
  src/pages/login/LoginPage.tsx
  src/vite-env.d.ts
Labels: ✨ Feature, 📬 API

#72 [FEAT] 헤더 반응형 등 기능 추가
  src/components/Header/Header.styles.ts
  src/components/Header/Header.tsx
Labels: ✨ Feature, 🎨 Html&css

#74 [FEAT] 검색 페이지 무한 스크롤 구현
  .github/ISSUE_TEMPLATE/custom.md
  .github/pull_request_template.md
  src/api/index.ts
  src/pages/Search/SearchPage.tsx
Labels: 🐞 BugFix

#75 [FIX] 검색 페이지 검색 페이지 초기화 디버그
  src/pages/Search/SearchPage.tsx
Labels: 🐞 BugFix

#76 [FEAT] 포트폴리오 작성 페이지 구현
  src/api/create-portfolio.ts
  src/api/upload-multiple-imgs.ts
  src/api/upload-single-img.ts
  src/components/Dropdown/DropdownWithBtn.tsx
  src/hooks/useTechStacksAndJobGroups.ts
  src/pages/EditPortfolio/EditPortfolioPage.styles.ts
  src/pages/EditPortfolio/EditPortfolioPage.tsx
  src/pages/EditPortfolio/MyCKEditor/MyCKEditor.tsx
  src/pages/EditPortfolio/TagInput/TagInput.tsx
  src/pages/EditPortfolio/ThumbnailInput/ThumbnailInput.tsx
  src/types/api-types/PortfolioType.ts
Labels: ✨ Feature

#77 [FEAT] 검색 페이지 무한 스크롤 디버그
  src/components/Header/Header.tsx
  src/pages/Search/SearchPage.tsx
Labels: 🐞 BugFix

#78 [Feat]메인페이지 섹션2 기능 추가
  src/components/PortfolioCard/PortfolioCard.style.tsx
  src/pages/Profile/ProfilePage.tsx
  src/pages/main/PopularPortfolioSection.tsx
  src/pages/main/PortfolioListSection.style.tsx
  src/pages/main/PortfolioListSection.tsx
Labels: ✨ Feature, 📬 API

#80 [FEAT] 프로필 페이지 EmptyPortfolio렌더링 버그 수정
  src/pages/Profile/ProfilePage.tsx
Labels: 🐞 BugFix

#82 [FEAT] 유저 프로필 등록 / 수정 페이지 구현 & 리팩토링
  src/api/create-profile.ts
  src/api/get-user-profile.ts
  src/api/upload-single-img.ts
  src/pages/EditProfile/EditProfilePage.tsx
  src/pages/EditProfile/UserInfoInputs.tsx
  src/pages/login/LoginPage.tsx
  src/types/api-types/UserType.ts
Labels: ✨ Feature, 🐞 BugFix, 📬 API, 🔨 Refactor

#85 [FEAT] 검색 페이지 기술 스택 선택 반영 버그 해결
  src/pages/Search/SearchPage.tsx
Labels: 🐞 BugFix

#92 🐛 수정 시 에디터 내용 불러오기&작성 버그 수정
  src/pages/Detail/DetailPage.styles.ts
  src/pages/Detail/DetailPage.tsx
  src/pages/EditPortfolio/EditPortfolioPage.tsx
  src/pages/EditPortfolio/MyCKEditor/MyCKEditor.tsx
Labels: 🐞 BugFix

#95 [FEAT] 디테일 페이지 PDF 내보내기 기능 추가
  package-lock.json
  package.json
  src/components/DetailPageButton/DetailPageButton.tsx
  src/pages/Detail/DetailPage.tsx
Labels: ✨ Feature

#98 [FIX] 검색 페이지 페이지네이션으로 전환, 메인페이지로 이동시 전역상태 반영 오류 수정
  src/components/TechStack2/TechStack2.styles.ts
  src/pages/Search/SearchPage.styles.ts
  src/pages/Search/SearchPage.tsx
  src/pages/main/GraphSection.tsx
  src/pages/main/PopularDeveloperSection.tsx
  src/pages/main/PortfolioListSection.tsx
Labels: 🐞 BugFix

#100 [DEBUG] detail page debug
  src/components/CommentBox/CommentBox.styles.ts
  src/pages/Detail/DetailPage.tsx
Labels: 🐞 BugFix

#101 [FEAT] 유저 프로필 업로드 API 구현
  src/api/index.ts
  src/api/upload-single-img.ts
  src/pages/EditProfile/EditProfilePage.tsx
  src/pages/login/GithubLoginBtn/GithubLoginBtn.tsx
Labels: ✨ Feature, 📬 API, 🔨 Refactor

#103 [FIX] 포폴 삭제 에러 수정
  src/pages/Detail/DetailPage.tsx
Labels: 🐞 BugFix

#104 🌏 Deploy
  src/pages/Detail/DetailPage.tsx
Labels: 🌏 Deploy

#106 [REFACTOR] 디테일 페이지 기술스택 개수 제한 삭제 및 스타일 리팩토링
  src/components/LikesAndViews/LikesAndViews.style.tsx
  src/components/LikesAndViews/LikesAndViews.tsx
  src/pages/Detail/DetailPage.styles.ts
  src/pages/Detail/DetailPage.tsx
Labels: 🎨 Html&css, 🔨 Refactor

#108 [FIX] 포트폴리오 수정 시 이미지 인덱스 버그 수정
  src/api/create-portfolio.ts
  src/api/upload-multiple-imgs.ts
Labels: 🐞 BugFix, 📬 API

#110 [FIX] 이미지 교체 순서 버그 수정
  src/api/create-portfolio.ts
Labels: 🐞 BugFix
